name: Release NPM package

on:
  push:
    tags: ['v*']

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Set tag
        id: tagName
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - run: npm ci

      # The .npmrc file can interfere with publishing:
      - run: rm .npmrc

      - name: Publish a release candidate
        if: contains(steps.tagName.outputs.tag, 'rc')
        run: npm publish --tag=rc --provenance

      - name: Publish a regular release
        if: false == contains(steps.tagName.outputs.tag, 'rc')
        run: npm publish --provenance

      # Put back .npmrc now that we are done:
      - run: git checkout -- .npmrc
